# config.yml for HR Bot

# Language for NLU
language: en

# Pipeline for NLU
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1


# Policies for dialogue management
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true

# Session configuration
session_config:
  session_expiration_time: 60  # minutes
  carry_over_slots_to_new_session: true
assistant_id: 20250904-143515-coral-antagonist
